### ISSUE TITLE
Give context in the response

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-run-query#204]
I played with the service and tried the list of SQL scripts like:

- https://adobeioruntime.net/api/v1/web/helix/helix-services/run-query@ci1100/most-visited?limit=20.
- https://adobeioruntime.net/api/v1/web/helix/helix-services/run-query@v2/next-resource?limit=20 (no result)
- https://adobeioruntime.net/api/v1/web/helix/helix-services/run-query@v2/error500?limit=20 (no result)
- https://adobeioruntime.net/api/v1/web/helix/helix-services/run-query@v2/top-blogposts?limit=20 (no result)
- https://adobeioruntime.net/api/v1/web/helix/helix-services/run-query@v2/top-pages?limit=20 (`Provided credentials are missing or invalid`)

Since I did not get a lot of results, I can only judge for the first (but I assume it is the same everywhere): there is no context in the response I get. I do not really know what I searched for, from when to when the search is valid... 
Would be great to add in the response:
- [ ] a description: a small text describing the search purpose
- [ ] the from / to applied
- [ ] ... any other relevant info that would self describe the result set.

**Comment by trieloff** [comment]
We can at least replay the applied parameters in the response, including possible empty parameters and default values.

Getting the description from the starting comment should be possible, too.

**Comment by MarquiseRosier** [comment]
Totally understand this req; and made a PR so we can stop shooting in the dark when we use run-query :)

**Comment by trieloff** [comment]
If you want to be extra cool, we could also allow a `.html` or `.txt` extension for the query URL, which would render just the documentation.
