### ISSUE TITLE
Proxyquire to stub responses from BigQuery

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-run-query#30]
We should use proxyquire instead of BigQuery for testing

**Comment by stefan-guggisberg** [comment]
Have you looked at [PollyJS](https://netflix.github.io/pollyjs/#/) or [Nock](https://github.com/nock/nock)?

We are using both in various Helix repos, e.g. https://github.com/adobe/helix-resolve-git-ref

**Comment by stefan-guggisberg** [comment]
If `@google-cloud/bigquery` is using the BigQuery REST API under the hood you could use [PollyJS](https://netflix.github.io/pollyjs/#/) to record/replay the BigQuery responses.
