### ISSUE TITLE
add ability for querying over range

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-run-query#32]
In the bigquery dataset; the tables are created on a daily basis; and follow the naming convention: requests[year][month]

For example, request201902 will be a table for some dataset and contains all requests for the month of February 2019. 

We should support querying over range of these tables; for some condition!

**Comment by trieloff** [comment]
I think the ideal implementation depends on the query. We might just get away with having a couple of shared default parameters like `@startdate` `@enddate`, `@limit`, `@from`, and then populate some of them with dynamic values.

**Comment by MarquiseRosier** [comment]
@trieloff https://github.com/adobe/helix-run-query/tree/date-replace
