### ISSUE TITLE
Allow Helix parameterized Queries

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-run-query#33]
**Please describe.**
Helix Run Query should be able to parameterize tablename, and columns. 

**Describe the solution you'd like**
The solution should protect against SQL injection! 

**Describe alternatives you've considered**
Google Bigquery parameterized queries do not allow this for column names, or tablenames. Also solution must clean all Helix Query Params; It is assumed that users will not provide excess parameters; but these are still detected and cleaned up.

**Comment by kptdobe** [comment]
> Additional context
> Add any other context or screenshots about the feature request here.

Just remove the sections for which you have no content to provide ;)

**Comment by stefan-guggisberg** [comment]
This issue has an open PR, reopening issue
