### ISSUE TITLE
Enable disabling of authentication

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-run-query#53]
As discussed in adobe/helix-pipeline#519:

- some queries should not require authentication
- especially those that are well-cached
- and don't disclose private information

Therefore, I'd add a feature similar to the `Cache-Control` (#12) comment like this:

```sql
--- Authorization: none
```

Possible values for the `Authorization` key could be `fastly` (default) and `none`.

**Comment by MarquiseRosier** [comment]
@trieloff let's say authorization is enabled; should we still try to get the service-id ourselves? Or should we force users to know this as part of the authorization process?
