### ISSUE TITLE
Allow weekly, monthly, quarterly, etc. aggregations for page views

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-run-query#611]
For low-volume sites, the daily page views report won't yield anything useful, so it would be great to be able to zoom out. Zooming out from one week of daily page views to one month of daily page views will just yield a more spiky pattern, so the optimal zoom should be two months of weekly page views (or one year of monthly page views).

This would require a new parameter `granularity` to become useful.

**Comment by davidnuescheler** [comment]
can this happen automatically based on the number of samples we have.... i am making up the numbers but if we didn't get `100` samples per `granularity` we would automatically uplevel to a "coarser" one...

**Comment by trieloff** [comment]
I knew you'd ask this. It's probably possible, but I cannot guess what the cost would be (in terms of SQL complexity)
