### ISSUE TITLE
treat 'www.' prefix as optional in RUM queries

### ISSUE THREAD

**Issue by langswei** [adobe/helix-run-query#940]
**Description**
Some queries treat www.domain.com the same as domain.com, while others do not.  We should make this behavior consistent, such that requests for domain.com data include www.domain.com implicitly.  The primary change for this is to helix_rum.EVENTS_V3 which is not in git.  My plan for now is to introduce EVENTS_V4 which handles the www and test a change to rum_dashboard.sql.  If it works out, will discuss rollout plans among the entire _V3 suite of table functions with @trieloff -- he may prefer a tested update be made directly to V3.

**To Reproduce**
Compare these two results:
- https://helix-pages.anywhere.run/helix-services/run-query@v3/rum-dashboard?domainkey=8e884fda-f644-4708-b583-a4b0715068cd&url=www.hlx.live
- https://helix-pages.anywhere.run/helix-services/run-query@v3/rum-dashboard?domainkey=8e884fda-f644-4708-b583-a4b0715068cd&url=hlx.live

**Expected behavior**
The 2nd URL above should have the same result as the first.

**Additional context**
The immediate beneficiary of this change will be an internal dashboard that lists domains without the www prefix but links to a RUM Dashboard page which currently handles with or without www differently.

**Comment by langswei** [comment]
The following two results are now equal:
- https://helix-pages.anywhere.run/helix-services/run-query@ci5735/rum-dashboard?domainkey=8e884fda-f644-4708-b583-a4b0715068cd&url=www.hlx.live
- https://helix-pages.anywhere.run/helix-services/run-query@ci5735/rum-dashboard?domainkey=8e884fda-f644-4708-b583-a4b0715068cd&url=hlx.live

The updated rum-dashboard query is at https://github.com/adobe/helix-run-query/blob/rum-dashboard-www/src/queries/rum-dashboard.sql

I will make a pull request after further discussion with the team regarding EVENTS_V3 vs. EVENTS_V4.

**Comment by trieloff** [comment]
`EVENTS_V3` is here: https://github.com/adobe/helix-run-query/blob/8f6e606520c2a5f852c29ea000d159e02610a3c8/src/queries/rum-common.sql#L88-L160

**Comment by trieloff** [comment]
I don't think treating apex and www the same is a good default, but I can imagine some marker like `.^hlx.live/$` to indicate that any subdomain is valid, or `www.^hlx.live/$` is valid. We already use `$` and `?` as suffixes, so `^` makes it look regex-y
